# Generated by Django 5.2.5 on 2025-11-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='paid', max_length=32),
        ),
    ]
