# Generated by Django 5.2.5 on 2025-11-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Paid', max_length=32),
        ),
    ]
