# Generated by Django 5.2.6 on 2025-12-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_orderitem_customization_review'),
        ('stores', '0004_alter_order_status'),
    ]

    operations = [
    ]
