# Generated by Django 5.2.5 on 2025-11-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_orderitem_customization_review'),
        ('stores', '0004_alter_order_status'),
    ]

    operations = [
    ]
