# Generated by Django 5.0 on 2025-12-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_merge_20251201_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drinks/'),
        ),
    ]
