# Generated by Django 5.0 on 2025-12-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_drink_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
