# Generated by Django 5.0 on 2025-12-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_drink_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='hours',
            field=models.TextField(blank=True, default='Mon-Fri 8:00 - 18:00'),
        ),
    ]
