# Generated by Django 5.0 on 2025-12-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_merge_20251203_0509'),
        ('stores', '0008_store_hours'),
    ]

    operations = [
    ]
