# Generated by Django 5.0 on 2025-12-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0009_merge_0005_merge_20251203_0509_0008_store_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="drink",
            name="price",
            field=models.IntegerField(default=500),
        ),
    ]
